---
name: Publish

on:
  push:
    tags:
      - "^\\d+[Rr]el\\d+$"

permissions: read-all

jobs:
  check-tag:
    name: Check Tag
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          fi
  test:
    uses: ./.github/workflows/validate-package.yml
    if: github.env.check-tag.outputs.match == 'true'
  publish_aur_package:
    name: Publish AUR package
    runs-on: ubuntu-latest
    needs: test
    if: github.env.check-tag.outputs.match == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Publish aarch64-none-elf-gcc-bin to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          pkgname: aarch64-none-elf-gcc-bin
          pkgbuild: ./aarch64-none-elf-gcc-aur/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update PKGBUILD to version ${{  github.ref_name }}"
          force_push: "true"
